#!/usr/bin/env bash
set -euo pipefail
export LC_ALL=C

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SOURCE_ROOT="$ROOT_DIR/Sources/LeafReaderApp"
# The core is a separate target now, but it is still this codebase — the wiki
# covers both roots or it stops describing the app.
CORE_ROOT="$ROOT_DIR/Sources/LeafReaderCore"
TEST_ROOT="$ROOT_DIR/Tests/LeafReaderTests"
OUT_DIR="${WIKI_OUT_DIR:-$ROOT_DIR/docs/wiki}"
OUT_FILE="$OUT_DIR/code-map.md"
TYPE_INDEX_FILE="$OUT_DIR/type-index.md"

mkdir -p "$OUT_DIR"

count_files() {
  find "$SOURCE_ROOT" "$CORE_ROOT" "$TEST_ROOT" "$ROOT_DIR/scripts" -type f \( -name '*.swift' -o -name '*.js' -o -name '*.sh' \) | wc -l | tr -d ' '
}

total_lines() {
  find "$SOURCE_ROOT" "$CORE_ROOT" "$TEST_ROOT" "$ROOT_DIR/scripts" -type f \( -name '*.swift' -o -name '*.js' -o -name '*.sh' \) -print0 \
    | xargs -0 wc -l \
    | tail -n 1 \
    | awk '{print $1}'
}

swift_lines() {
  find "$SOURCE_ROOT" "$CORE_ROOT" -name '*.swift' -print0 \
    | xargs -0 wc -l \
    | tail -n 1 \
    | awk '{print $1}'
}

write_largest_files() {
  find "$SOURCE_ROOT" "$CORE_ROOT" "$TEST_ROOT" "$ROOT_DIR/scripts" -type f \( -name '*.swift' -o -name '*.js' -o -name '*.sh' \) -print0 \
    | xargs -0 wc -l \
    | sort -nr \
    | head -n 20 \
    | awk -v root="$ROOT_DIR/" '{
        if ($2 == "total") next;
        path=$2;
        sub(root, "", path);
        printf "| `%s` | %s |\n", path, $1
      }'
}

write_matching_files() {
  local title="$1"
  local pattern="$2"
  echo "## $title"
  echo
  find "$SOURCE_ROOT" "$CORE_ROOT" -type f -name "$pattern" -print \
    | sed "s#$ROOT_DIR/##" \
    | sort \
    | awk '{ printf "- `%s`\n", $0 }'
  echo
}

write_swift_types() {
  # The access modifier is optional so that `LeafReaderCore`'s `package` types
  # are indexed. Without it the whole core silently disappeared from the index,
  # which looked exactly like "the core declares nothing".
  grep -rnE "^(package |public |open |internal )?(final class|class|struct|enum|protocol|extension) " \
    --include='*.swift' "$SOURCE_ROOT" "$CORE_ROOT" \
    | sed "s#$ROOT_DIR/##" \
    | sort \
    | awk -F: '{ printf "| `%s` | %s | `%s` |\n", $1, $2, $3 }'
}

cat > "$OUT_FILE" <<EOF
# Code Map

Generated by \`./scripts/generate_code_wiki.sh\`.

## Summary

- Code files: $(count_files)
- Main code lines: $(total_lines)
- Swift app lines: $(swift_lines)
- Full Swift type index: [Type Index](type-index.md)

## Largest Files

| File | Lines |
| --- | ---: |
$(write_largest_files)

$(write_matching_files "Reader Window Modules" "ReaderWindowController*.swift")
$(write_matching_files "AI Chat Modules" "AIChatPanel*.swift")
$(write_matching_files "Document Loading Modules" "DocumentLoading*.swift")
$(write_matching_files "Recent Documents Modules" "RecentDocuments*.swift")
EOF

cat > "$TYPE_INDEX_FILE" <<EOF
# Type Index

Generated by \`./scripts/generate_code_wiki.sh\`.

## Swift Type Index

| File | Line | Declaration |
| --- | ---: | --- |
$(write_swift_types)
EOF

echo "Generated $OUT_FILE"
echo "Generated $TYPE_INDEX_FILE"
